from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class CommonMolecule:
    """Immutable descriptor of a common polyatomic anion, ligand or solvent with SMILES, χ_dia and SDF file."""

    formula: str
    name: str
    SMILES: set[str]
    diamag_sus: float
    sdf_file: str
    description: Optional[str] = ""

    def __str__(self) -> str:
        smiles_str = ", ".join(sorted(self.SMILES))
        return (
            f"sdf_file='{self.sdf_file}', "
            f"formula='{self.formula}', "
            f"SMILES={{{smiles_str}}}, "
            f"diamag_sus={self.diamag_sus}"
        )


"""
unit: 10^(-6) cm^3/mol
Reference (DOI): 10.1021/ed085p532 (TABLE 5)
This dictionary represents the diamagnetic susceptibilities for common molecules (solvents, ions and ligands).

@note1: Only canonical SMILES are provided, which were generated using RDKit Chem.MolToSmiles().
The same RDKit function was utilized to generate SMILES from SDF. In this way, unambiguous comparison between SMILES from SDF and the dictionary is possible.
@note2: For aromatic molecules, one of the resonance structures should be provided in an input SDF file.
Hybrid structures with shown aromaticity are prone to failure and should be used with caution by the users.
@note3: Thiosulfate (S2O32-) is an important exception, with two canonical SMILES related to different bonding of terminal sulphur atom in resonance structures.
@note4: RDKit does not support SMILES with double bonds for hypervalent halogen oxoions.
As a result, the generated SMILES for BrO3-, ClO3-, ClO4-, IO3- and IO4- ions do not reflect their correct structures.
@note5: For BF4- anion, the negative charge must be located on the boron atom. Otherwise SDF fails to parse.
@note6: In the reference (Table 3), PO4(3-) anion was incorrectly written as PO3(3-).
@note7: PtCl6(2-) (Table 3 in the reference) was intentionally omited in the dictionary.
@note8: Our software does not support stereochemical structures.
@note9: carbonyl (CO) ligand must be drawn with (+) charge located on C and (-) on O. Otherwise, SDF fails to parse.

Here's a breakdown of the values:
"""

COMMON_MOLECULES = {
    "ions": [
        CommonMolecule(
            formula="AsO3(3-)",
            name="arsenate(III)",
            SMILES={"[O-][As]([O-])[O-]"},
            diamag_sus=-51,
            sdf_file="AsO33-.sdf",
        ),
        CommonMolecule(
            formula="AsO4(3-)",
            name="arsenate(V)",
            SMILES={"O=[As]([O-])([O-])[O-]"},
            diamag_sus=-60,
            sdf_file="AsO43-.sdf",
        ),
        CommonMolecule(
            formula="BF4(-)",
            name="tetrafluoroborate",
            SMILES={"F[B-](F)(F)F"},
            diamag_sus=-37,
            sdf_file="BF4-.sdf",
        ),
        CommonMolecule(
            formula="BO3(3-)",
            name="borate",
            SMILES={"[O-]B([O-])[O-]"},
            diamag_sus=-35,
            sdf_file="BO33-.sdf",
        ),
        CommonMolecule(
            formula="BrO3(-)",
            name="bromate(V)",
            SMILES={"[O-][Br+2]([O-])[O-]"},
            diamag_sus=-40,
            sdf_file="BrO3-.sdf",
        ),
        CommonMolecule(
            formula="ClO3(-)",
            name="chlorate(V)",
            SMILES={"[O-][Cl+2]([O-])[O-]"},
            diamag_sus=-30.2,
            sdf_file="ClO3-.sdf",
        ),
        CommonMolecule(
            formula="ClO4(-)",
            name="chlorate(VII)",
            SMILES={"[O-][Cl+3]([O-])([O-])[O-]"},
            diamag_sus=-32.0,
            sdf_file="ClO4-.sdf",
        ),
        CommonMolecule(
            formula="CN(-)",
            name="cyanide",
            SMILES={"[C-]#N"},
            diamag_sus=-13.0,
            sdf_file="CN-.sdf",
        ),
        CommonMolecule(
            formula="C5H5(-)",
            name="cyclopentadienyl",
            SMILES={"c1cc[cH-]c1"},
            diamag_sus=-65,
            sdf_file="C5H5-.sdf",
        ),
        CommonMolecule(
            formula="C6H5COO(-)",
            name="benzoate",
            SMILES={"O=C([O-])c1ccccc1"},
            diamag_sus=-71,
            sdf_file="C6H5COO-.sdf",
        ),
        CommonMolecule(
            formula="CO3(2-)",
            name="carbonate",
            SMILES={"O=C([O-])[O-]"},
            diamag_sus=-28.0,
            sdf_file="CO32-.sdf",
        ),
        CommonMolecule(
            formula="C2O4(2-)",
            name="oxalate",
            SMILES={"O=C([O-])C(=O)[O-]"},
            diamag_sus=-34,
            sdf_file="C2O42-.sdf",
        ),
        CommonMolecule(
            formula="HCOO(-)",
            name="formate",
            SMILES={"O=C[O-]"},
            diamag_sus=-17,
            sdf_file="HCOO-.sdf",
        ),
        CommonMolecule(
            formula="IO3(-)",
            name="iodate(V)",
            SMILES={"[O-][I+2]([O-])[O-]"},
            diamag_sus=-51,
            sdf_file="IO3-.sdf",
        ),
        CommonMolecule(
            formula="IO4(-)",
            name="iodate(VII)",
            SMILES={"[O-][I+3]([O-])([O-])[O-]"},
            diamag_sus=-51.9,
            sdf_file="IO4-.sdf",
        ),
        CommonMolecule(
            formula="NO2(-)",
            name="nitrate(III)",
            SMILES={"O=N[O-]"},
            diamag_sus=-10.0,
            sdf_file="NO2-.sdf",
        ),
        CommonMolecule(
            formula="NO3(-)",
            name="nitrate(V)",
            SMILES={"O=[N+]([O-])[O-]"},
            diamag_sus=-18.9,
            sdf_file="NO3-.sdf",
        ),
        CommonMolecule(
            formula="NCO(-)",
            name="cyanate",
            SMILES={"N#C[O-]"},
            diamag_sus=-23,
            sdf_file="NCO-.sdf",
        ),
        CommonMolecule(
            formula="NCS(-)",
            name="thiocyanate",
            SMILES={"N#C[S-]"},
            diamag_sus=-31.0,
            sdf_file="NCS-.sdf",
        ),
        CommonMolecule(
            formula="OAc(-)",
            name="acetate",
            SMILES={"CC(=O)[O-]"},
            diamag_sus=-31.5,
            sdf_file="AcO-.sdf",
        ),
        CommonMolecule(
            formula="OH(-)",
            name="hydroxide",
            SMILES={"[OH-]"},
            diamag_sus=-12.0,
            sdf_file="OH-.sdf",
        ),
        CommonMolecule(
            formula="PO4(3-)",
            name="phosphate",
            SMILES={"O=P([O-])([O-])[O-]"},
            diamag_sus=-42,
            sdf_file="PO43-.sdf",
        ),
        CommonMolecule(
            formula="SO3(2-)",
            name="sulfate(IV)",
            SMILES={"O=S([O-])[O-]"},
            diamag_sus=-38,
            sdf_file="SO32-.sdf",
        ),
        CommonMolecule(
            formula="SO4(2-)",
            name="sulfate(VI)",
            SMILES={"O=S(=O)([O-])[O-]"},
            diamag_sus=-40.1,
            sdf_file="SO42-.sdf",
        ),
        CommonMolecule(
            formula="S2O3(2-)",
            name="thiosulfate",
            SMILES={"O=S(=O)([O-])[S-]", "O=S([O-])([O-])=S"},
            diamag_sus=-46,
            sdf_file="S2O32-.sdf",
        ),
        CommonMolecule(
            formula="S2O8(2-)",
            name="peroxydisulfate",
            SMILES={"O=S(=O)([O-])OOS(=O)(=O)[O-]"},
            diamag_sus=-78,
            sdf_file="S2O82-.sdf",
        ),
        CommonMolecule(
            formula="HSO4(-)",
            name="bisulfate",
            SMILES={"O=S(=O)([O-])O"},
            diamag_sus=-35.0,
            sdf_file="HSO4-.sdf",
        ),
        CommonMolecule(
            formula="SeO3(2-)",
            name="selenite",
            SMILES={"O=[Se]([O-])[O-]"},
            diamag_sus=-44,
            sdf_file="SeO32-.sdf",
        ),
        CommonMolecule(
            formula="SeO4(2-)",
            name="selenate",
            SMILES={"O=[Se](=O)([O-])[O-]"},
            diamag_sus=-51,
            sdf_file="SeO42-.sdf",
        ),
        CommonMolecule(
            formula="SiO3(2-)",
            name="silicate",
            SMILES={"O=[Si]([O-])[O-]"},
            diamag_sus=-36,
            sdf_file="SiO32-.sdf",
        ),
        CommonMolecule(
            formula="TeO3(2-)",
            name="tellurite",
            SMILES={"O=[Te]([O-])[O-]"},
            diamag_sus=-63,
            sdf_file="TeO32-.sdf",
        ),
        CommonMolecule(
            formula="TeO4(2-)",
            name="tellurate",
            SMILES={"O=[Te](=O)([O-])[O-]"},
            diamag_sus=-55,
            sdf_file="TeO42-.sdf",
        ),
    ],
    "ligands": [
        CommonMolecule(
            formula="acac-",
            name="acetylacetonate",
            SMILES={"CC(=O)C=C(C)[O-]"},
            diamag_sus=-52,
            sdf_file="acac-.sdf",
        ),
        CommonMolecule(
            formula="bipy",
            name="2,2′-bipyridine",
            SMILES={"c1ccc(-c2ccccn2)nc1"},
            diamag_sus=-105,
            sdf_file="bipy.sdf",
        ),
        CommonMolecule(
            formula="CO",
            name="carbonyl",
            SMILES={"[C-]#[O+]"},
            diamag_sus=-10,
            sdf_file="CO.sdf",
        ),
        CommonMolecule(
            formula="en",
            name="ethylenediamine",
            SMILES={"NCCN"},
            diamag_sus=-46.5,
            sdf_file="en.sdf",
        ),
        CommonMolecule(
            formula="C2H4",
            name="ethylene",
            SMILES={"C=C"},
            diamag_sus=-15,
            sdf_file="ethylene.sdf",
        ),
        CommonMolecule(
            formula="gly",
            name="glycinate",
            SMILES={"NCC(=O)[O-]"},
            diamag_sus=-37,
            sdf_file="glycinate.sdf",
        ),
        CommonMolecule(
            formula="H2O",
            name="water",
            SMILES={"O"},
            diamag_sus=-13,
            sdf_file="water.sdf",
        ),
        CommonMolecule(
            formula="H2N-NH2",
            name="hydrazine",
            SMILES={"NN"},
            diamag_sus=-20,
            sdf_file="hydrazine.sdf",
        ),
        CommonMolecule(
            formula="mal",
            name="malonate",
            SMILES={"O=C([O-])CC(=O)[O-]"},
            diamag_sus=-45,
            sdf_file="malonate.sdf",
        ),
        CommonMolecule(
            formula="NH3",
            name="ammonia",
            SMILES={"N"},
            diamag_sus=-18,
            sdf_file="ammonia.sdf",
        ),
        CommonMolecule(
            formula="phen",
            name="phenanthroline",
            SMILES={"c1cnc2c(c1)ccc1cccnc12"},
            diamag_sus=-128,
            sdf_file="phen.sdf",
        ),
        CommonMolecule(
            formula="o-PBMA",
            name="o-phenylenebisdimethylarsine",
            SMILES={"C[As](C)c1ccccc1[As](C)C"},
            diamag_sus=-194,
            sdf_file="o-PBMA.sdf",
        ),
        CommonMolecule(
            formula="H2Pc",
            name="phthalocyanine",
            SMILES={
                "c1ccc2c(c1)-c1nc-2nc2[nH]c(nc3nc(nc4[nH]c(n1)c1ccccc41)-c1ccccc1-3)c1ccccc21"
            },
            diamag_sus=-442,
            sdf_file="phthalocyanine.sdf",
        ),
        CommonMolecule(
            formula="PPh3",
            name="triphenylphosphine",
            SMILES={"c1ccc(P(c2ccccc2)c2ccccc2)cc1"},
            diamag_sus=-167,
            sdf_file="PPh3.sdf",
        ),
        CommonMolecule(
            formula="pyz",
            name="pyrazine",
            SMILES={"c1cnccn1"},
            diamag_sus=-50,
            sdf_file="pyrazine.sdf",
        ),
        CommonMolecule(
            formula="py",
            name="pyridine",
            SMILES={"c1ccncc1"},
            diamag_sus=-49,
            sdf_file="pyridine.sdf",
        ),
        CommonMolecule(
            formula="sal(2-)",
            name="salen2-",
            SMILES={"[O-]c1ccccc1C=NCCN=Cc1ccccc1[O-]"},
            diamag_sus=-182,
            sdf_file="salen2-.sdf",
        ),
        CommonMolecule(
            formula="urea",
            name="urea",
            SMILES={"NC(N)=O"},
            diamag_sus=-34,
            sdf_file="urea.sdf",
        ),
    ],
    "organic_solvents": [
        CommonMolecule(
            formula="CCl4",
            name="tetrachloromethane",
            SMILES={"ClC(Cl)(Cl)Cl"},
            diamag_sus=-66.8,
            sdf_file="CCl4.sdf",
        ),
        CommonMolecule(
            formula="CHCl3",
            name="chloroforom",
            SMILES={"ClC(Cl)Cl"},
            diamag_sus=-58.9,
            sdf_file="CHCl3.sdf",
        ),
        CommonMolecule(
            formula="CH2Cl2",
            name="dichloromethane",
            SMILES={"ClCCl"},
            diamag_sus=-46.6,
            sdf_file="CH2Cl2.sdf",
        ),
        CommonMolecule(
            formula="CH3Cl",
            name="chloromethane",
            SMILES={"CCl"},
            diamag_sus=-32.0,
            sdf_file="CH3Cl.sdf",
        ),
        CommonMolecule(
            formula="CH3NO2",
            name="nitromethane",
            SMILES={"C[N+](=O)[O-]"},
            diamag_sus=-21.0,
            sdf_file="CH3NO2.sdf",
        ),
        CommonMolecule(
            formula="CH3OH",
            name="methanol",
            SMILES={"CO"},
            diamag_sus=-21.4,
            sdf_file="CH3OH.sdf",
        ),
        CommonMolecule(
            formula="CCl3COOH",
            name="trichloroacetic acid",
            SMILES={"O=C(O)C(Cl)(Cl)Cl"},
            diamag_sus=-73.0,
            sdf_file="CCl3COOH.sdf",
        ),
        CommonMolecule(
            formula="CF3COOH",
            name="trifluoroacetic acid",
            SMILES={"O=C(O)C(F)(F)F"},
            diamag_sus=-43.3,
            sdf_file="CF3COOH.sdf",
        ),
        CommonMolecule(
            formula="CH3CN",
            name="acetonitrile",
            SMILES={"CC#N"},
            diamag_sus=-27.8,
            sdf_file="CH3CN.sdf",
        ),
        CommonMolecule(
            formula="1,2-CH2Cl2",
            name="1,2-dichloroethane",
            SMILES={"ClCCCl"},
            diamag_sus=-59.6,
            sdf_file="ClCH2CH2Cl.sdf",
        ),
        CommonMolecule(
            formula="CH3COOH",
            name="acetic acid",
            SMILES={"CC(=O)O"},
            diamag_sus=-31.8,
            sdf_file="CH3COOH.sdf",
        ),
        CommonMolecule(
            formula="CH3CH2OH",
            name="ethanol",
            SMILES={"CCO"},
            diamag_sus=-33.7,
            sdf_file="CH3CH2OH.sdf",
        ),
        CommonMolecule(
            formula="HOCH2CH2OH",
            name="ethylene glycol",
            SMILES={"OCCO"},
            diamag_sus=-38.9,
            sdf_file="HOCH2CH2OH.sdf",
        ),
        CommonMolecule(
            formula="CH3CH2SH",
            name="ethanethiol",
            SMILES={"CCS"},
            diamag_sus=-44.9,
            sdf_file="CH3CH2SH.sdf",
        ),
        CommonMolecule(
            formula="CH3C(=O)CH3",
            name="acetone",
            SMILES={"CC(C)=O"},
            diamag_sus=-33.8,
            sdf_file="CH3COCH3.sdf",
        ),
        CommonMolecule(
            formula="CH3C(=O)OC(=O)CH3",
            name="acetic anhydride",
            SMILES={"CC(=O)OC(C)=O"},
            diamag_sus=-52.8,
            sdf_file="CH3CO_O_OCCH3.sdf",
        ),
        CommonMolecule(
            formula="CH3CH2CH2CN",
            name="butyronitrile",
            SMILES={"CCCC#N"},
            diamag_sus=-50.4,
            sdf_file="CH3CH2CH2CN.sdf",
        ),
        CommonMolecule(
            formula="CH3C(=O)OCH2CH3",
            name="ethyl acetate",
            SMILES={"CCOC(C)=O"},
            diamag_sus=-54.1,
            sdf_file="CH3CO_OCH2CH3.sdf",
        ),
        CommonMolecule(
            formula="CH3CH2CH2CH2OH",
            name="butanol",
            SMILES={"CCCCO"},
            diamag_sus=-56.4,
            sdf_file="CH3CH2CH2CH2OH.sdf",
        ),
        CommonMolecule(
            formula="CH3CH2OCH2CH3",
            name="diethyl ether",
            SMILES={"CCOCC"},
            diamag_sus=-55.5,
            sdf_file="CH3CH2OCH2CH3.sdf",
        ),
        CommonMolecule(
            formula="CH3CH2CH2CH2CH3",
            name="pentane",
            SMILES={"CCCCC"},
            diamag_sus=-61.5,
            sdf_file="CH3CH2CH2CH2CH3.sdf",
        ),
        CommonMolecule(
            formula="1,2-C6H4Cl2",
            name="o-dichlorobenzene",
            SMILES={"Clc1ccccc1Cl"},
            diamag_sus=-84.4,
            sdf_file="o-C6H4Cl2.sdf",
        ),
        CommonMolecule(
            formula="C6H6",
            name="benzene",
            SMILES={"c1ccccc1"},
            diamag_sus=-54.8,
            sdf_file="C6H6.sdf",
        ),
        CommonMolecule(
            formula="C6H12",
            name="cyclohexane",
            SMILES={"C1CCCCC1"},
            diamag_sus=-68,
            sdf_file="C6H12.sdf",
        ),
        CommonMolecule(
            formula="CH3CH2CH2CH2CH2CH3",
            name="hexane",
            SMILES={"CCCCCC"},
            diamag_sus=-74.1,
            sdf_file="CH3CH2CH2CH2CH2CH3.sdf",
        ),
        CommonMolecule(
            formula="N(CH2CH3)3",
            name="triethylamine",
            SMILES={"CCN(CC)CC"},
            diamag_sus=-83.3,
            sdf_file="N_CH2CH3_3.sdf",
        ),
        CommonMolecule(
            formula="PhCN",
            name="benzonitrile",
            SMILES={"N#Cc1ccccc1"},
            diamag_sus=-65.2,
            sdf_file="PhCN.sdf",
        ),
        CommonMolecule(
            formula="PhCH3",
            name="toluene",
            SMILES={"Cc1ccccc1"},
            diamag_sus=-65.6,
            sdf_file="PhCH3.sdf",
        ),
        CommonMolecule(
            formula="CH3C(CH3)2CH2CH(CH3)2",
            name="isooctane",
            SMILES={"CC(C)CC(C)(C)C"},
            diamag_sus=-99.1,
            sdf_file="isooctane.sdf",
        ),
        CommonMolecule(
            formula="C10H8",
            name="naphthaline",
            SMILES={"c1ccc2ccccc2c1"},
            diamag_sus=-91.6,
            sdf_file="naphthaline.sdf",
        ),
    ],
}
