[tox]
envlist = py{3.12}, build, nuitka-py{3.12}
isolated_build = True

labels = 
  test = py{3.12}
  build = build
  test-all = py{3.12}
  compile-all = nuitka-py{3.12}
  build-all = build, nuitka-py{3.12}
  ci-all = py{3.12}, build, nuitka-py{3.12}

[testenv:.pkg]
setenv = 
  PYTHONPATH = {toxinidir}
passenv = 
  SETUPTOOLS_SCM_PRETEND_VERSION

[testenv]
setenv = 
  PYTHONPATH = {toxinidir}{:}{toxinidir}{/}mcpmenago{:}{toxinidir}{/}tests
passenv = 
  SETUPTOOLS_SCM_PRETEND_VERSION
commands = 
  python -m pytest tests/ --html=tests/reports/TEST_REPORT_{envname}.html --self-contained-html

deps = 
  -rrequirements-dev.txt

[testenv:build]
skip_install = True
deps = build
commands =
  python -m build --sdist --wheel --outdir dist/

[testenv:nuitka-py{3.12}]
basepython = 
  py3.12: python3.12
skip_install = True
deps = 
  nuitka
  wheel
  setuptools
  setuptools_scm
commands = 
  python -c "import shutil; shutil.rmtree('build', ignore_errors=True)"
  python setup.py bdist_nuitka --dist-dir=dist
