from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from src.core.atom import MBAtom
    from src.core.molecule import MBMolecule


class ConstProvider:
    @staticmethod
    def GetPascalValues(atom: "MBAtom") -> dict[str, float]:
        """Looks up relevant Pascal Constant data for given atom."""
        covalent = PASCAL_CONST.get(atom.symbol, {}).get("covalent", {})
        ionic = PASCAL_CONST.get(atom.symbol, {}).get("ionic", {})

        values = {
            "open_chain": covalent.get("open_chain"),
            "ring": covalent.get("ring"),
            "ox_state": covalent.get("ox_state", {}).get(atom.ox_state),
            "charge": ionic.get("charge", {}).get(atom.charge),
        }

        # Remove keys that are not present. Missing key means that no data was found for given atom.
        return {k: v for k, v in values.items() if v is not None}

    @staticmethod
    def GetRelevantRingAtoms() -> list[str]:
        return RELEVANT_RING_ATOMS

    @staticmethod
    def GetRelevantOxidationAtoms() -> list[str]:
        return RELEVANT_OXIDATION_ATOMS

    @staticmethod
    def GetDiamagContr(mol: "MBMolecule") -> float:
        """Returns diamag contribution of common molecules."""

        # TODO: Finish.
        return ...


"""
unit: 10^(-6) cm^3/mol
Reference (DOI): 10.1021/ed085p532 (TABLE 5)
This dictionary represents the diamagnetic susceptibilities for common solvent molecules used for crystallization.
Here's a breakdown of the values:
"""
# For some molecules, more than one SMILES notation is possible.
# For simplicity, only one SMILES notation was included for each molecule in the dictionary.
# The SMILES strings found in PubChem may not be canonical.
# To ensure consistency, all SMILES in the dictionary were generated by RDKit using the MolFromSmiles function.
# The same function is used to generate SMILES for molecules from SDF file,
# which makes the comparison between dictionary SMILES and SDF-derived SMILES valid.

COMMON_SOLVENTS = {
    "CCl4": {
        "Name": "tetrachloromethane",
        "SMILES": "ClC(Cl)(Cl)Cl",
        "DIAMAG_SUS": -66.8,
    },
    "CHCl3": {
        "Name": "chloroforom",
        "SMILES": "ClC(Cl)Cl",
        "DIAMAG_SUS": -58.9,
    },
    "CH2Cl2": {
        "Name": "dichloromethane",
        "SMILES": "ClCCl",
        "DIAMAG_SUS": -46.6,
    },
    "CH3Cl": {
        "Name": "chloromethane",
        "SMILES": "CCl",
        "DIAMAG_SUS": -32.0,
    },
    "CH3NO2": {
        "Name": "nitromethane",
        "SMILES": "C[N+](=O)[O-]",
        "DIAMAG_SUS": -21.0,  # The overall molecule has neutral charge
    },
    "CH3OH": {
        "Name": "methanol",
        "SMILES": "CO",
        "DIAMAG_SUS": -21.4,
    },
    "CCl3COOH": {
        "Name": "trichloroacetic acid",
        "SMILES": "O=C(O)C(Cl)(Cl)Cl",
        "DIAMAG_SUS": -73.0,
    },
    "CF3COOH": {
        "Name": "trifluoroacetic acid",
        "SMILES": "O=C(O)C(F)(F)F",
        "DIAMAG_SUS": -43.3,
    },
    "CH3CN": {
        "Name": "acetonitrile",
        "SMILES": "CC#N",
        "DIAMAG_SUS": -27.8,
    },
    "1,2-CH2Cl2": {
        "Name": "1,2-dichloroethane",
        "SMILES": "ClCCCl",
        "DIAMAG_SUS": -59.6,
    },
    "CH3COOH": {
        "Name": "acetic acid",
        "SMILES": "CC(=O)O",
        "DIAMAG_SUS": -31.8,
    },
    "CH3CH2OH": {
        "Name": "ethanol",
        "SMILES": "CCO",
        "DIAMAG_SUS": -33.7,
    },
    "HOCH2CH2OH": {
        "Name": "ethylene glycol",
        "SMILES": "OCCO",
        "DIAMAG_SUS": -38.9,
    },
    "CH3CH2SH": {
        "Name": "ethanethiol",
        "SMILES": "CCS",
        "DIAMAG_SUS": -44.9,
    },
    "CH3C(=O)CH3": {
        "Name": "acetone",
        "SMILES": "CC(C)=O",
        "DIAMAG_SUS": -33.8,
    },
    "CH3C(=O)OC(=O)CH3": {
        "Name": "acetic anhydride",
        "SMILES": "CC(=O)OC(C)=O",
        "DIAMAG_SUS": -52.8,
    },
    "CH3CH2CH2CN": {
        "Name": "butyronitrile",
        "SMILES": "CCCC#N",
        "DIAMAG_SUS": -50.4,
    },
    "CH3C(=O)OCH2CH3": {
        "Name": "ethyl acetate",
        "SMILES": "CCOC(C)=O",
        "DIAMAG_SUS": -54.1,
    },
    "CH3CH2CH2CH2OH": {
        "Name": "butanol",
        "SMILES": "CCCCO",
        "DIAMAG_SUS": -56.4,
    },
    "CH3CH2OCH2CH3": {
        "Name": "diethyl ether",
        "SMILES": "CCOCC",
        "DIAMAG_SUS": -55.5,
    },
    "CH3CH2CH2CH2CH3": {
        "Name": "pentane",
        "SMILES": "CCCCC",
        "DIAMAG_SUS": -61.5,
    },
    "1,2-C6H4Cl2": {
        "Name": "o-dichlorobenzene",
        "SMILES": "Clc1ccccc1Cl",
        "DIAMAG_SUS": -84.4,
    },
    "C6H6": {
        "Name": "benzene",
        "SMILES": "c1ccccc1",
        "DIAMAG_SUS": -54.8,
    },
    "C6H12": {
        "Name": "cyclohexane",
        "SMILES": "C1CCCCC1",
        "DIAMAG_SUS": -68,
    },
    "CH3CH2CH2CH2CH2CH3": {
        "Name": "hexane",
        "SMILES": "CCCCCC",
        "DIAMAG_SUS": -74.1,
    },
    "N(CH2CH3)3": {
        "Name": "triethylamine",
        "SMILES": "CCN(CC)CC",
        "DIAMAG_SUS": -83.3,
    },
    "PhCN": {
        "Name": "benzonitrile",
        "SMILES": "N#Cc1ccccc1",
        "DIAMAG_SUS": -65.2,
    },
    "PhCH3": {
        "Name": "toluene",
        "SMILES": "Cc1ccccc1",
        "DIAMAG_SUS": -65.6,
    },
    "CH3C(CH3)2CH2CH(CH3)2": {
        "Name": "isooctane",
        "SMILES": "CC(C)CC(C)(C)C",
        "DIAMAG_SUS": -99.1,
    },
    "C10H8": {
        "Name": "naphthaline",
        "SMILES": "c1ccc2ccccc2c1",
        "DIAMAG_SUS": -91.6,
    },
}

"""Lists of atoms for which it was specified that the atom may be part of a ring or has a defined oxidation state, according to 10.1021/ed085p532 (DOI)"""
RELEVANT_OXIDATION_ATOMS = ["As", "Hg", "Pb"]
RELEVANT_RING_ATOMS = ["N", "C"]


"""
unit: 10^(-6) cm^3/mol
Reference (DOI): 10.1021/ed085p532 (TABLES 1 and 6, and some anions from TABLE 3)
This dictionary represents the diamagnetic values for elements in
different bonding/oxidation_state/ionic_charge scenarios. Here's a breakdown of the values:
"""
PASCAL_CONST = {
    "C": {
        "covalent": {
            "ring": -6.24,
            "open_chain": -6.0,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                4: -0.1,
            },
        },
    },
    "H": {
        "covalent": {
            "ring": None,
            "open_chain": -2.93,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                1: 0,
                -1: -5.7,
            },
        },
    },
    "N": {
        "covalent": {
            "ring": -4.61,
            "open_chain": -5.57,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                5: -0.1,
            },
        },
    },
    "Ag": {
        "covalent": {
            "ring": None,
            "open_chain": -31.0,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                1: -28,
                2: -24,  # uncetrain value according to the article (DOI: 10.1021/ed085p532)
            },
        },
    },
    "Al": {
        "covalent": {
            "ring": None,
            "open_chain": -13.0,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -2,
            },
        },
    },
    "As": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {
                3: -20.9,
                5: -43.0,
            },
        },
        "ionic": {
            "charge": {
                3: -9,  # uncetrain value according to the article (DOI: 10.1021/ed085p532)
                5: -6,
            },
        },
    },
    "Au": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                1: -40,  # uncetrain value according to the article (DOI: 10.1021/ed085p532)
                3: -32,
            },
        },
    },
    "B": {
        "covalent": {
            "ring": None,
            "open_chain": -7.0,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -0.2,
            },
        },
    },
    "Ba": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -26.5,
            },
        },
    },
    "Be": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -0.4,
            },
        },
    },
    "Bi": {
        "covalent": {
            "ring": None,
            "open_chain": -192.0,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -25,  # uncetrain value according to the article (DOI: 10.1021/ed085p532)
                5: -23,
            },
        },
    },
    "Br": {
        "covalent": {
            "ring": None,
            "open_chain": -30.6,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                -1: -34.6,
                5: -6,
            },
        },
    },
    "Ca": {
        "covalent": {
            "ring": None,
            "open_chain": -15.9,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -10.4,
            },
        },
    },
    "Cd": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -24,
            },
        },
    },
    "Ce": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -20,
                4: -17,
            },
        },
    },
    "Cl": {
        "covalent": {
            "ring": None,
            "open_chain": -20.1,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                -1: -23.4,
                5: -2,
            },
        },
    },
    "Co": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -12,
                3: -10,
            },
        },
    },
    "Cr": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -15,
                3: -11,
                4: -8,
                5: -5,
                6: -3,
            },
        },
    },
    "Cs": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                1: -35.0,
            },
        },
    },
    "Cu": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                1: -12,
                2: -11,
            },
        },
    },
    "Dy": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -19,
            },
        },
    },
    "Er": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -18,
            },
        },
    },
    "Eu": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -22,
                3: -20,
            },
        },
    },
    "F": {
        "covalent": {
            "ring": None,
            "open_chain": -6.3,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                -1: -9.1,
            },
        },
    },
    "Fe": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -13,
                3: -10,
            },
        },
    },
    "Ga": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -8,
            },
        },
    },
    "Ge": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                4: -7,
            },
        },
    },
    "Gd": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -20,
            },
        },
    },
    "Hf": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                4: -16,
            },
        },
    },
    "Hg": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {
                2: -33.0,
            },
        },
        "ionic": {
            "charge": {
                2: -40.0,
            },
        },
    },
    "Ho": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -19,
            },
        },
    },
    "I": {
        "covalent": {
            "ring": None,
            "open_chain": -44.6,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                -1: -50.6,
                5: -12,
                7: -10,
            },
        },
    },
    "In": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -19,
            },
        },
    },
    "Ir": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                1: -50,
                2: -42,
                3: -35,
                4: -29,
                5: -20,
            },
        },
    },
    "K": {
        "covalent": {
            "ring": None,
            "open_chain": -18.5,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                1: -14.9,
            },
        },
    },
    "La": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -20,
            },
        },
    },
    "Li": {
        "covalent": {
            "ring": None,
            "open_chain": -4.2,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                1: -1.0,
            },
        },
    },
    "Lu": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -17,
            },
        },
    },
    "Mg": {
        "covalent": {
            "ring": None,
            "open_chain": -10.0,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -5.0,
            },
        },
    },
    "Mn": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -14,
                3: -10,
                4: -8,
                6: -4,
                7: -3,
            },
        },
    },
    "Mo": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -31,
                3: -23,
                4: -17,
                5: -12,
                6: -7,
            },
        },
    },
    "Na": {
        "covalent": {
            "ring": None,
            "open_chain": -9.2,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                1: -6.8,
            },
        },
    },
    "Nb": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                5: -9,
            },
        },
    },
    "Nd": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -20,
            },
        },
    },
    "Ni": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -12,
            },
        },
    },
    "O": {
        "covalent": {
            "ring": None,
            "open_chain": -4.6,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                -2: -12.0,  # The value of χDi for O2– is reported as –6.0 in some sources
            },
        },
    },
    "Os": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -44,
                3: -36,
                4: -29,
                6: -18,
                8: -11,
            },
        },
    },
    "P": {
        "covalent": {
            "ring": None,
            "open_chain": -26.3,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -4,
                5: -1,
            },
        },
    },
    "Pb": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {
                2: -46.0,
            },
        },
        "ionic": {
            "charge": {
                2: -32.0,
                4: -26,
            },
        },
    },
    "Pd": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -25,
                4: -18,
            },
        },
    },
    "Pm": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -27,
            },
        },
    },
    "Pr": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -20,
                4: -18,
            },
        },
    },
    "Pt": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -40,
                3: -33,
                4: -28,
            },
        },
    },
    "Rb": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                1: -22.5,
            },
        },
    },
    "Re": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -36,
                4: -28,
                6: -16,
                7: -12,
            },
        },
    },
    "Rh": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -22,
                4: -18,
            },
        },
    },
    "Ru": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -23,
                4: -18,
            },
        },
    },
    "S": {
        "covalent": {
            "ring": None,
            "open_chain": -15.0,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                -2: -30,
                4: -3,
                6: -1,
            },
        },
    },
    "Sb": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {
                3: -74.0,
            },
        },
        "ionic": {
            "charge": {
                3: -17,
                5: -14,
            },
        },
    },
    "Sc": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -6,
            },
        },
    },
    "Se": {
        "covalent": {
            "ring": None,
            "open_chain": -23.0,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                -2: -48,  # This value is uncertain
                4: -8,
                6: -5,
            },
        },
    },
    "Si": {
        "covalent": {
            "ring": None,
            "open_chain": -13,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                4: -1,
            },
        },
    },
    "Sm": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -23,
                3: -20,
            },
        },
    },
    "Sn": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {
                4: -30,
            },
        },
        "ionic": {
            "charge": {
                2: -20,
                4: -16,
            },
        },
    },
    "Sr": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -19.0,
            },
        },
    },
    "Ta": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                5: -14,
            },
        },
    },
    "Tb": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -19,
                4: -17,
            },
        },
    },
    "Te": {
        "covalent": {
            "ring": None,
            "open_chain": -37.3,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                -2: -70,
                4: -14,
                6: -12,
            },
        },
    },
    "Th": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                4: -23,
            },
        },
    },
    "Ti": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -9,
                4: -5,
            },
        },
    },
    "Tl": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {
                1: -40.0,
            },
        },
        "ionic": {
            "charge": {
                1: -35.7,
                3: -31,
            },
        },
    },
    "Tm": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -18,
            },
        },
    },
    "U": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -46,
                4: -35,
                5: -26,
                6: -19,
            },
        },
    },
    "V": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -15,
                3: -10,
                4: -7,
                5: -4,
            },
        },
    },
    "W": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -41,
                3: -36,
                4: -23,
                5: -19,
                6: -13,
            },
        },
    },
    "Y": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                3: -12,
            },
        },
    },
    "Yb": {
        "covalent": {
            "ring": None,
            "open_chain": None,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -20,
                3: -18,
            },
        },
    },
    "Zn": {
        "covalent": {
            "ring": None,
            "open_chain": -13.5,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                2: -15.0,
            },
        },
    },
    "Zr": {
        "covalent": {
            "ring": None,
            "open_chain": -13.5,
            "ox_state": {},
        },
        "ionic": {
            "charge": {
                4: -10,
            },
        },
    },
}

METAL_CATIONS = [
    "Au",
    "Ba",
    "Be",
    "Cd",
    "Ce",
    "Co",
    "Cr",
    "Cs",
    "Cu",
    "Dy",
    "Er",
    "Eu",
    "Fe",
    "Ga",
    "Ge",
    "Gd",
    "Hf",
    "Ho",
    "In",
    "Ir",
    "La",
    "Lu",
    "Mn",
    "Mo",
    "Nb",
    "Ni",
    "Os",
    "Pd",
    "Pm",
    "Pr",
    "Pt",
    "Rb",
    "Re",
    "Rh",
    "Ru",
    "Sc",
    "Sm",
    "Sr",
    "Ta",
    "Tb",
    "Th",
    "Ti",
    "Tm",
    "U",
    "V",
    "W",
    "Y",
    "Yb",
    "Zr",
]
