name: Auto-Assign PR Author

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: pr-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true

jobs:
  assign-author:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Assign PR to its author
        uses: peter-evans/assign-issue@v3
        with:
          assignees: ${{ github.actor }}
